SwapDeals/Models/Advertisement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapDeals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Advertisement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advertisement()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int AdID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> UserID { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name="Sell Product")]
        public string SellingProduct { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Target Product")]
        public string TargatedProduct { get; set; }
        [Display(Name = "Date")]
        public Nullable<System.DateTime> Date { get; set; }
        [Display(Name = "Add / Pay (+ve Means buyer will add)")]
        public Nullable<int> AdjustedValue { get; set; }
        
        [Display(Name = "Upload image")]
        public string Images { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public string ProductDescription { get; set; }
        public Nullable<int> PriorityStatus { get; set; }
        public Nullable<int> Payment { get; set; }
        [Required]
        public string Warranty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}

SwapDeals/Controllers/AdvertisementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SwapDeals.Models;

namespace SwapDeals.Controllers
{
    public class AdvertisementsController : Controller
    {
        private SwapDealsDBEntities db = new SwapDealsDBEntities();

        public ActionResult Index()
        {

            if(Session["admin"]==null)
                return RedirectToAction("Index", "Home");
            var advertisements = db.Advertisements.Include(a => a.Product).Include(a => a.User);
            return View(advertisements.ToList());
        }
       
        public ActionResult Details(int? id)
        {
            HttpContext.Response.Cache.SetExpires(DateTime.UtcNow.AddYears(-1));
            HttpContext.Response.Cache.SetValidUntilExpires(false);
            HttpContext.Response.Cache.SetRevalidation(HttpCacheRevalidation.AllCaches);
            HttpContext.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            HttpContext.Response.Cache.SetNoStore();
            HttpContext.Response.ExpiresAbsolute = DateTime.UtcNow.Subtract(new TimeSpan(1, 0, 0, 0));
            HttpContext.Response.Expires = 0;
            HttpContext.Response.Cache.AppendCacheExtension("no-store, no-cache, must-revalidate, proxy-revalidate, post-check=0, pre-check=0");
            if (Session["user_id"] == null)
            {
                if(Session["admin"] == null)
                  return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (Session["user_id"] != null)
            {
                var temp = db.Bookings.SqlQuery("Select * from Booking ").ToList<Booking>();
                int flag = 0;
                //  ValueTuple t1 = db.Database.ExecuteSqlCommand("Select *from Advertisements where AdID in (Select AdID from Booking)").
                foreach (var b in temp)
                {
                    if(b.AdID==id)
                    {
                        flag = 1;
                    }
                }
                ViewData["booked"] = flag;
            }
            else
                ViewData["booked"] = 1;

            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }

       
        [HttpGet]
        public ActionResult Create()
        {
            HttpContext.Response.Cache.SetExpires(DateTime.UtcNow.AddYears(-1));
            HttpContext.Response.Cache.SetValidUntilExpires(false);
            HttpContext.Response.Cache.SetRevalidation(HttpCacheRevalidation.AllCaches);
            HttpContext.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            HttpContext.Response.Cache.SetNoStore();
            HttpContext.Response.ExpiresAbsolute = DateTime.UtcNow.Subtract(new TimeSpan(1, 0, 0, 0));
            HttpContext.Response.Expires = 0;
            HttpContext.Response.Cache.AppendCacheExtension("no-store, no-cache, must-revalidate, proxy-revalidate, post-check=0, pre-check=0");
            if (Session["user_id"] == null)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Advertisement ad)
        {
            if (Session["user_id"] == null)
                return RedirectToAction("Index", "Home");

            if (ModelState.IsValid)
            {
                ad.UserID = Convert.ToInt32(Session["user_id"]);
                
                
               var pid = db.Products
                                   .SqlQuery("Select * from Products where ProductName = @id", new SqlParameter("@id",ad.SellingProduct))
                                    .FirstOrDefault();
                if(pid==null)
                {
                    Product P = new Product();
                    P.ProductName =ad.SellingProduct;
                    P.ProductDetails = ad.ProductDescription;
                    P.ProductPrice = 0;
                    P.ProductBrand = "";
                    P.ProductCategory = "";
                    try
                    {
                        db.Products.Add(P);
                        db.SaveChanges();
                        pid = db.Products
                                   .SqlQuery("Select * from Products where ProductName = @id", new SqlParameter("@id", ad.SellingProduct))
                                    .FirstOrDefault();

                    }
                    catch(Exception e)
                    {
                        return Content(e.ToString());
                    }

                }
                ad.ProductID = Convert.ToInt32(pid.ProductID);
              // ad.ProductID=
                ad.PriorityStatus = -2;
                ad.Payment = 0;
                string fileName = Path.GetFileNameWithoutExtension(ad.ImageFile.FileName);
                string extension = Path.GetExtension(ad.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                ad.Images = "~/Content/images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/images/"), fileName);
                ad.ImageFile.SaveAs(fileName);
               
                    try
                    {
                        db.Advertisements.Add(ad);
                        db.SaveChanges();
                        return Content("Ad posted successfully .Wait fo approval");
                    }
                    catch (Exception e)
                    {
                        return Content("Something went wrong");
                    }
              
            }
            return Content("Try again");


        }
        
        [HttpGet]
        public ActionResult Ads()
        {
            HttpContext.Response.Cache.SetExpires(DateTime.UtcNow.AddYears(-1));
            HttpContext.Response.Cache.SetValidUntilExpires(false);
            HttpContext.Response.Cache.SetRevalidation(HttpCacheRevalidation.AllCaches);
            HttpContext.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            HttpContext.Response.Cache.SetNoStore();
            HttpContext.Response.ExpiresAbsolute = DateTime.UtcNow.Subtract(new TimeSpan(1, 0, 0, 0));
            HttpContext.Response.Expires = 0;
            HttpContext.Response.Cache.AppendCacheExtension("no-store, no-cache, must-revalidate, proxy-revalidate, post-check=0, pre-check=0");
            using (db)
            {
               
                var ads = db.Advertisements.SqlQuery("Select *from Advertisements where PriorityStatus>-1")
                      .ToList<Advertisement>();
              
                ViewData["Ads"] = ads;
                return View();
            }
            
        }
        [HttpPost]

        public ActionResult Ads(TempAds ta)
        {
            if(ModelState.IsValid)
            {
               
                var ads = db.Advertisements.SqlQuery("Select *from Advertisements where TargatedProduct like '%"
                    +(ta.SellingProduct ?? "%")+"%' and SellingProduct like '%"+(ta.TargatedProduct ?? "%")+"%'"+ " and PriorityStatus > -1 ")
                      .ToList<Advertisement>();
                //string t= "Select *from Advertisements where TargatedProduct like '%"
                  //  + (ta.SellingProduct ?? "%") + "%' and SellingProduct like '%" + (ta.TargatedProduct ?? "%") + "%'" +" and PriorityStatus > -1";
              //  System.Diagnostics.Debug.WriteLine(t); 
                if (ads==null)
                {
                    return RedirectToAction("Index","Home");
                }
                else
                {
                  
                    ViewData["Ads"] = ads;
                    return View();
                }

            }
             
             return View();
        }
        public ActionResult PostedAds()
        {
            HttpContext.Response.Cache.SetExpires(DateTime.UtcNow.AddYears(-1));
            HttpContext.Response.Cache.SetValidUntilExpires(false);
            HttpContext.Response.Cache.SetRevalidation(HttpCacheRevalidation.AllCaches);
            HttpContext.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            HttpContext.Response.Cache.SetNoStore();
            HttpContext.Response.ExpiresAbsolute = DateTime.UtcNow.Subtract(new TimeSpan(1, 0, 0, 0));
            HttpContext.Response.Expires = 0;
            HttpContext.Response.Cache.AppendCacheExtension("no-store, no-cache, must-revalidate, proxy-revalidate, post-check=0, pre-check=0");

            if (Session["user_id"] == null)
                return RedirectToAction("Index", "Home");
            var a = db.Advertisements.SqlQuery("Select * from Advertisements where UserID = " + Convert.ToInt32(Session["user_id"])+" and PriorityStatus >-2").ToList<Advertisement>();
            return View("Index", a);
        }
        [HttpGet]
        public ActionResult EditUserAd(int? id)
        {
            if (Session["user_id"] == null)
                return RedirectToAction("Index", "Home");
            Session["AdID"] = id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisements.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
           
            return View(advertisement);
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUserAd(Advertisement advertisement)
        {

SwapDeals/Views/Advertisements/Ads.cshtml
@using SwapDeals.Models
@model SwapDeals.Models.TempAds
@{
    ViewBag.Title = "Ads";
}
<div class="row" >
    <hr />
    <div class="col-lg-4"> </div>
    <div class="col-lg-4">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TargatedProduct, new { htmlAttributes = new { placeholder = " Enter targeted product", @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TargatedProduct, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SellingProduct, new { htmlAttributes = new { placeholder = " Enter selling product", @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SellingProduct, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Search" class="btn btn-success btn-block" />
                    </div>

                </div>


            </div>
        }
    </div>
    <div class="col-lg-4"> </div>
</div>
<div class="hot-product">
    <div class="container">
        <div class="all-tag">
            <h2>Search Result</h2>
        </div>
        <div class="row">
            @foreach (var ad in ViewData["Ads"] as IEnumerable<Advertisement>)
            {
                if (Convert.ToInt32(Session["user_id"]) != ad.UserID)
                {
                    <div class="col-md-4">
                        <div class="hot-item-top">
                            <img src="@Url.Content(ad.Images)" class="img-fluid" alt="pic">
                            <div class="hot-overlay">
                                @if (Session["user_id"] == null)
                                {

                                    <input type="button" value="Details" class="btn btn-primary" onclick="alert('Login to continue')" />

                                }
                                else
                                {


                                    <input type="button" value="Details" class="btn btn-primary" onclick="location.href = '@Url.Action("Details/" + ad.AdID, "Advertisements")'" />
                                   

                                }

                            </div>
                        </div>
                        <div class="hot-item-bottom">
                            <h5>Selling @ad.SellingProduct</h5>
                            <h6>Want @ad.TargatedProduct</h6>
                        </div>
                    </div>
                }
            }

        </div>

    </div>
</div>

SwapDeals/Views/Advertisements/Create.cshtml
@model SwapDeals.Models.Advertisement

@{
    ViewBag.Title = "Post Ad";
}

<h2>Post Ad</h2>

@using (Html.BeginForm("Create", "Advertisements", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Advertisement</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.SellingProduct, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SellingProduct, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellingProduct, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TargatedProduct, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TargatedProduct, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TargatedProduct, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdjustedValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdjustedValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdjustedValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" type="file" name="ImageFile" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            @Html.LabelFor(model => model.Warranty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Warranty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Warranty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SwapDeals/Views/Advertisements/Delete.cshtml
@model SwapDeals.Models.Advertisement

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Advertisement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SellingProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellingProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TargatedProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TargatedProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdjustedValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdjustedValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriorityStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriorityStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Warranty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SwapDeals/Views/Advertisements/Details.cshtml
@using SwapDeals.Models
@model SwapDeals.Models.Advertisement

@{
   
    ViewBag.Title = "Details";
    int f = (int)ViewData["Booked"];
}

<h2>Details</h2>

<div>
    <h4>Advertisement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SellingProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SellingProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TargatedProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TargatedProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdjustedValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdjustedValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd>

            <img src="@Url.Content(Model.Images)" class="img-fluid" alt="pic" height="350" width="350">

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriorityStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriorityStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Warranty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User.UserEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserEmail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User.UserPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserPhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User.UserAdress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserAdress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Rating)
        </dd>

    </dl>
</div>
<p>
    @if (Session["admin"] != null)
    {

        @Html.ActionLink("Edit", "Edit", new { id = Model.AdID }) <h5> </h5>
        @Html.ActionLink("Back to List", "Index") 

    }
    else
    {

        @Html.ActionLink("Back", "Ads") <h5> </h5>
        if (Convert.ToInt32(Session["user_id"]) != Model.UserID  && f==0)
        {
            <input type="button" value="Book" class="btn btn-primary" onclick="location.href = '@Url.Action("Book/" + Model.AdID, "Bookings")'" />
        }

    }
</p>

SwapDeals/Views/Advertisements/Edit.cshtml
@model SwapDeals.Models.Advertisement

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Advertisement</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AdID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductID, "ProductID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SellingProduct, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SellingProduct, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SellingProduct, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TargatedProduct, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TargatedProduct, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TargatedProduct, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdjustedValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdjustedValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdjustedValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Images, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Images, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriorityStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriorityStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriorityStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Payment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Payment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Payment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Warranty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Warranty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Warranty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>